import pandas as pd

dict_region = pd.DataFrame()
dict_region['Allen'] = ['AON',
                        'Dorsal tenia tecta, layer 1',
                        'Dorsal tenia tecta, layer 4', 
                        'MOB', 
                        'OLF', 
                        'OT',
                        'TTd',
                        'TTv',

                        'FRP5', 
                        'FRP6a',  
                        'ORBl1',  
                        'ORBl2/3',  
                        'ORBl5',  
                        'ORBl6a',  
                        'ORBl6b',  
                        'ORBm2/3', 
                        'ORBm5', 
                        'ORBvl1',
                        'ORBvl2/3', 
                        'ORBvl5', 
                        
                        'DP',  
                        'ILA2/3',  
                        'ILA5',  
                        'ILA6a',  
                        'PL1',  
                        'PL2/3',  
                        'PL5',  
                        'PL6a',  
                        'PL6b',                   
                        
                        
                        'ACAd5',  
                        'ACAd6a',  
                        'ACAv2/3',  
                        'ACAv5',  
                        'Cingulate cortex, area 25 (dorsal peduncular cortex), layer1',  
                        'Cingulate cortex, area 25 (dorsal peduncular cortex), layer5',  
                        'Cingulate cortex, area 25 (dorsal peduncular cortex), layer6a',                         
                                                
                        'MOp1',  
                        'MOp2/3',  
                        'MOp5',  
                        'MOp6a',  
                        'MOp6b',  
                        'MOs2/3',  
                        'MOs5',  
                        'MOs6a',  
                        'MOs6b',

                        'Primary somatosensory cortex layer 6a',  
                        'Primary somatosensory cortex layer 6b',  
                        'Primary somatosensory cortex, upper lip region, layer 6b',  
                        'SSp-bfd5',  
                        'SSp-bfd6a',  
                        'SSp-bfd6b',  
                        'SSp-n6a',  
                        'SSp-n6b',  
                        'SSp-un2/3',  
                        'SSp-un4',  
                        'SSp-un5',  
                        'SSp-un6a',  
                        'SSp-un6b',  

                        'Caudoputamen- caudal, dorsal, dorsolateral', 
                        'Caudoputamen- caudal, intermediate, dorsal', 
                        'Caudoputamen- caudal, ventral', 
                        'Caudoputamen- intermediate, dorsolateral, dorsal', 
                        'Caudoputamen- intermediate, dorsolateral, intermedial dorsal', 
                        'Caudoputamen- rostral, lateral, lateral strip',

                        'Caudoputamen- caudal, dorsal, dorsomedial', 
                        'Caudoputamen- intermediate, dorsomedial, central dorsal', 
                        'Caudoputamen- intermediate, dorsomedial, dorsal tip', 
                        'Caudoputamen- intermediate, dorsomedial, dorsolateral', 
                        'Caudoputamen- intermediate, dorsomedial, intermedial', 
                        'Caudoputamen- rostral extreme', 
                        'Caudoputamen- rostral, intermediate, dorsal', 
                        'Caudoputamen- rostral, medial', 

                        'Caudoputamen- caudal, intermediate, ventrolateral', 
                        'Caudoputamen- caudal, intermediate, ventromedial', 
                        'Caudoputamen- intermediate, ventrolateral, central ventrolateral', 
                        'Caudoputamen- intermediate, ventrolateral, intermedial ventral', 
                        'Caudoputamen- intermediate, ventrolateral, ventral', 
                        'Caudoputamen- intermediate, ventrolateral, ventral tip', 
                        'Caudoputamen- intermediate, ventromedial, central ventromedial', 
                        'Caudoputamen- intermediate, ventromedial, ventral', 
                        'Caudoputamen- intermediate, ventromedial, ventromedial', 
                        'Caudoputamen- rostral, intermediate, ventral', 
                        'Caudoputamen- rostra,l lateral, ventromedial', 
                        'Striatum ventral region', 

                        'Accumbens nucleus, core region',

                        'Accumbens nucleus, shell region',
                        'Lateral accumbens, shell region',

                        'FS', 
                        'MA', 
                        'PAL', 
                        'SI',


                        'IA', 
                        'BMAa', 
                        'BST', 
                        'CEAc', 
                        'CEAl', 
                        'CEAm', 
                        'COAa', 
                        'Extension of the amygdala', 
                        'Interstitial nucleus of the posterior limb of the anterior commissure, lateral part', 
                        'Interstitial nucleus of the posterior limb of the anterior commissure, medial part', 
                        'MEA', 

                        'LSr', 
                        'LSv', 
                        'Lateral septal nucleus, dorsal part', 
                        'Lateral septal nucleus, intermediate part', 
                        'MS', 
                        'Medial septal nucleus', 

                        'LD', 
                        'RT', 
                        'VAL', 
                        'VPL', 
                        'VPM', 

                        'AHN', 
                        'HY', 
                        'LHA', 
                        'LPO', 
                        'MPN', 
                        'MPO', 
                        'PS', 
                        'PeF', 
                        'ZI', 

                        'Claustrum', 
                        'Dorsal endopiriform nucleus', 
                        'Dysgranular insular cortex, layer 6b', 
                        'Granular insular cortex, layer 6b', 
                        'Intermediate endopiriform claustrum', 
                        'GPi', 
                        'NDB',  
                        'Navicular nucleus of the basal forebrain',  
                        'Nucleus of the vertical limb of the diagonal band',  

                        'aco',  
                        'act',  
                        'anterior commissure, anterior part',  
                        'ccb',  
                        'ccg',  
                        'chpl',  
                        'cing',  
                        'corpus callosum',  
                        'em',  
                        'external capsule',  
                        'fa',  
                        'fiber tracts',  
                        'forceps minor of the corpus callosum',  
                        'fx',  
                        'genu of the corpus callosum',  
                        'int',  
                        'lateral ventricle',  
                        'root',  
                        'scwm',  
                        'SEZ',  
                        'VL'  
                        ]
dict_region['Summary_Region'] = ['Olfactory Areas',
                        'Olfactory Areas',
                        'Olfactory Areas', 
                        'Olfactory Areas', 
                        'Olfactory Areas', 
                        'Olfactory Areas',
                        'Olfactory Areas',
                        'Olfactory Areas',
                        
                        'Frontal Cortex', 
                        'Frontal Cortex',  
                        'Frontal Cortex',  
                        'Frontal Cortex',  
                        'Frontal Cortex',  
                        'Frontal Cortex',  
                        'Frontal Cortex',  
                        'Frontal Cortex', 
                        'Frontal Cortex', 
                        'Frontal Cortex',
                        'Frontal Cortex', 
                        'Frontal Cortex',                         
                        
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  
                        'Prefrontal Cortex',  

                        'Cingulate Cortex',  
                        'Cingulate Cortex',  
                        'Cingulate Cortex',  
                        'Cingulate Cortex',  
                        'Cingulate Cortex',  
                        'Cingulate Cortex',  
                        'Cingulate Cortex', 

                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  
                        'Motor Cortex',  

                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  
                        'Sensory Cortex',  

                        'Dorsolateral Striatum', 
                        'Dorsolateral Striatum', 
                        'Dorsolateral Striatum', 
                        'Dorsolateral Striatum', 
                        'Dorsolateral Striatum', 
                        'Dorsolateral Striatum',


                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',
                        'Dorsomedial Striatum',

                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',
                        'Ventral Striatum',

                        'Nucleus Accumbens Core',

                        'Nucleus Accumbens Shell',
                        'Nucleus Accumbens Shell',

                        'Ventral Pallidum', 
                        'Ventral Pallidum', 
                        'Ventral Pallidum', 
                        'Ventral Pallidum',

                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 
                        'Amygdala', 

                        'Septum', 
                        'Septum', 
                        'Septum', 
                        'Septum', 
                        'Septum', 
                        'Septum', 

                        'Thalamus', 
                        'Thalamus', 
                        'Thalamus', 
                        'Thalamus', 
                        'Thalamus', 


                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 
                        'Hypothalamus', 

                        'Other Areas', 
                        'Other Areas', 
                        'Other Areas', 
                        'Other Areas', 
                        'Other Areas', 
                        'Other Areas', 
                        'Other Areas',  
                        'Other Areas',  
                        'Other Areas',

                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts',  
                        'Fiber Tracts'
                        ]
